name: get lastest boc term posts from vietcetera

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # At 00:00 every day
env:
  # Setting an environment variable with the value of a configuration variable
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          cd notion_vietcetera
          python vietcetera_boc_term.py
      - uses: minhkhuong2404/notion-vietcetera@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "main"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: ""
          # AUTO_PUSH is optional, a boolean variable default to true, whether automatically push generated files to desired branch
          AUTO_PUSH: true
